development:
  adapter: postgresql
  database: Clark_Travel_dev
  host: localhost
  username: Doug
  password: ENV['DOUG_PW']
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: Clark_Travel_test
  host: localhost
  username: Doug
  password: ENV['DOUG_PW']