# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(first_name: "Douglas", last_name: "Teixeira", email: "teixeir3@gmail.com", password: ENV["ADMIN_PASSWORD"])

# user.testimonials.create(highlight: "", body: "", signature: "", display: true, position: 17)
user.testimonials.create({highlight: "Thank You", body: "Words cannot express how grateful we are for all your hard work during our wedding planning. Your professionalism dealing with our frequent questions always put us at ease in a stressful time. You made things simple & easy to understand for us and our guests. Our only wish was that you could have joined us at this beautiful resort. Thank you again for helping to create memories that will last a lifetime.", signature: "Nate and Trish", display: true, position: 0})

user.testimonials.create({highlight: "We had a wonderful time", body: "Our recent cruise aboard the Caribbean Princess was perfect in every way. The luxury of the ship, beauty of the beaches and scenery of the islands can only be described as breathtaking. Our gratitude for your service, recommendations and advice cannot be overstated. Your thoughtful gifts that awaited us in our stateroom were deeply appreciated. Thank you so much. We had a wonderful time and, it would be a safe bet to say that we will be cruising again.", signature: "Al & Karen Jurgensen
", display: true, position: 1})

user.testimonials.create(highlight: "First cruise", body: "I want to sincerely thank you very much for all your efforts which made my first cruise an enjoyable and memorable experience. You found me a great flight and selected an awesome room for me. Then you went beyond the call of duty when you cancelled and rebooked our cruise reservations at a cost savings. You treated me as a human being every step of the way - not just another number in your files. I'm glad Joanne found and chose you as our travel agent. Your professionalism in the field is outstanding.", signature: "Donald R. Shriadek", display: true, position: 2)
user.testimonials.create(highlight: "Namibia", body: "Thank you very much for all the great work you do for me in planning my vacations! I want to especially thank you for finding the Namibia tour that meet my needs. I never imagined I would actually be going to Namibia, but you have made my dream come true! You always go above and beyond in supporting my travel plans. You’re a gem!", signature: "Mary Ciufo-lind", display: true, position: 3)
user.testimonials.create(highlight: "Looking forward to our trip", body: "Thank you very much for the wing you gifted us on our cruise. It was a very nice gesture and ewe enjoyed having it with out dinners. Most of all we would like to express our appreciation for you service and professionalism. We are more than please how you handled the logistics of trips and have recommended you to family and friends. We are looking forward to having you take care of our next trip!", signature: "The Rivera Family", display: true, position: 4)
user.testimonials.create(highlight: "Paris", body: "Thank you so very much for making Our first trip to Paris' wonderful, beautiful, magnificent and memorable. It was one of our dreams come true!!", signature: "Patti & Mike Haller", display: true, position: 5)
user.testimonials.create(highlight: "Rivera Maya", body: "Just wanted to tell you how wonderful our trip was to Secret's Capri. Everything was exquisite from the moment we arrived until we sadly had to leave. The staff at Secret's Capri were spot on as well as friendly. I think between staff and other vacationers, our mom adopted six additional kids. Everyone called her mom. We were treated so nicely by everyone on staff who catered to our every need, joked and laughed with us. The food was delicious. We dined in every restaurant. The weather was spectacular my sister and I even parasailed that was awesome.", signature: "", display: true, position: 6)
user.testimonials.create(highlight: "Thanks again!!!", body: "Thank you again for making such wonderful travel arrangements for us. You never disappoint and we greatly appreciate all of you efforts in making sure we have a great vacation. This one was truly special as it was the first time all daughters and mom went away together and we have fabulous memories to carry with us.", signature: "Ursula Deeg-Dube", display: true, position: 7)
user.testimonials.create(highlight: "Louisiana was great!", body: "Thanks so much for helping us with our trip to Louisiana! You don't know how much we appreciate it. The trip was a lot of fun and we wouldn't have been able to make it without your help. We know you must've pulled some strings or called in a favor. Keep working your magic! We can't continue going on so many vacations without your help!!", signature: "Laura Juliano & Doug Teixeira", display: true, position: 8)
user.testimonials.create(highlight: "Family trip", body: "Thank you so much for a wonderful trip for my family and myself. I will think of your for our next trip.", signature: "Elizabeth Veit", display: true, position: 9)
user.testimonials.create(highlight: "Alaska", body: "We want to tell you what a wonderful time we both had on our trip to Alaska! WOW! Thank you for all you did to make this our most memorable vacation yet. We also want to thank you for the Alaska Cruise Companion book and map. We enjoyed reading it on the cruise and following our trip on the map. And thank you for the gift of a bottle of wine! We had a nice dinner at Sterling Steakhouse on Jeff’s birthday and enjoyed the wine. We are looking forward to our next cruise in October. It will be so nice to see you again.", signature: "", display: true, position: 10)
user.testimonials.create(highlight: "Hooked", body: "Ann and I are very grateful for the work you do every time we shoot you an email. The kinds of customer service you routinely provide seems like a dying art. If you haven’t figured it out already, you have me hooked as a lifetime client.", signature: "David", display: true, position: 11)
user.testimonials.create(highlight: "Wonderful Trip", body: "I want to thank you for all your work and attention to details in making our trip so wonderful. It was quite an adventure and we all had such a great time. Thanks for everything and we will use your services again in the future.", signature: "Gail", display: true, position: 12)
user.testimonials.create(highlight: "Sandals", body: "I just wanted to let you know what an incredible time Brandon and I had at Sandals in Nassau!! You were rightit was amazing! We loved every minute and we’re afraid we’re spoiled now…we don’t want to be let down by future vacations after staying at such a great place! Good food, friendly staff, great beach, LOVED the private island! Thanks again for all of your help with the trip! Greg mentioned you requested the room upgrade for us thank you so much! Our villa suite was so great – we loved staying in the garden area with a nice semi-private pool right outside our door! I just gave a friend, Kimberly, you contact information. She’s getting married and doesn’t where she wants to go on a honeymoon. I told her you could make the recommendations based on what she and her fiancée are looking for. Thanks again.", signature: "Megan", display: true, position: 13)
user.testimonials.create(highlight: "Disney Cruise", body: "We returned this past Saturday from our Disney Cruise. Everything went exceptionally well. Thank you for all your patience and assistance. As well as for the lovely treats you surprised us with in our rooms. They were very well received. We will happily refer our friends and family to your agency!", signature: "Bonnie & Paul", display: true, position: 14)
user.testimonials.create(highlight: "Beauty of Alaska", body: "Thank you so very much for your thoughtfulness as I prepared for my trip to Alaska. The experience was amazing: words cannot express the beauty, awesome and grandeur of this part of our country. Please know that your gift was used to make this time enjoyable for me and my family. I will always be gratefully for you thoughtfulness.", signature: "Fr. Len", display: true, position: 15)
user.testimonials.create(highlight: "Trip to Prague", body: "Just wanted to thank you for putting together such a wonderful trip. Privatair was everything you promised and more - in fact, our return flight arrived in Newark an hour early. And John and I fell in love with Prague and its genteel old world charm. The weather was spectacular; hotel lovely, people gracious. We walked the entire time, never took a taxi or tram and chose the day trip rather than the chateau tour. In fact, the movie the Illusionist, which we watched on the flight home, was filmed there. Our time in Prague will be forever etched in our memory and we will continue to (and have been) singing its praises since our return.", signature: "Janet L.", display: true, position: 16)

